### ISSUE TITLE
Формируются пакеты без перевода каретки (\r)

### ISSUE THREAD

**Issue by escapism9** [banzalik/har2ammo#21]
субж
Использую стандартный конфиг

**Comment by banzalik** [comment]
привет, можно пример конфига, версию har2amoo, har файл и получившийся результат?

**Comment by escapism9** [comment]
Привет!
Проверял на 0.2.0 и на 0.3.4. Забрать har и ammo можно тут - http://vk.cc/3ELIYz

**Comment by banzalik** [comment]
Исправлено в версии 0.3.5

**Comment by escapism9** [comment]
Привет!
Проблема еще актуальна. 0.3.5, использовал тот же har. 
Новый ammo тут - http://vk.cc/3EZtsM

Разница между изначальным ammo и новым есть, конечно, но запрос все еще не соответствует стандартному запросу http. В gitter'е можно обсудить детальнее, если есть желание.

**Comment by escapism9** [comment]
0.3.7 - ok! )
